# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 10:14
from __future__ import unicode_literals

from django.db import migrations, models
import django_unixdatetimefield.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lottery',
            fields=[
                ('created_at', django_unixdatetimefield.fields.UnixDateTimeField(blank=True)),
                ('token', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('duration', models.IntegerField(default=30)),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LotteryPlayer',
            fields=[
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('identity', models.IntegerField(primary_key=True, serialize=False)),
                ('token', models.UUIDField(default=uuid.uuid4)),
            ],
        ),
    ]
