# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 10:15
from __future__ import unicode_literals

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('submits', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='created_at',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_created=True),
        ),
    ]
