# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 10:16
from __future__ import unicode_literals

from django.db import migrations
import django_unixdatetimefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('submits', '0002_auto_20160430_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lottery',
            name='created_at',
            field=django_unixdatetimefield.fields.UnixDateTimeField(auto_now=True),
        ),
    ]
