# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-30 12:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submits', '0003_auto_20160430_1316'),
    ]

    operations = [
        migrations.AddField(
            model_name='lottery',
            name='winner_row',
            field=models.IntegerField(default=-1),
        ),
    ]
